// Actual finite-budget momentum-SignSGD trajectories, double precision.
// Gaussian draws and initializations are generated by the accompanying Python
// script with numpy.default_rng, then shared across all candidate rates/CNRs.
#include <algorithm>
#include <atomic>
#include <cmath>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <numeric>
#include <string>
#include <thread>
#include <vector>

struct Draws {
  size_t paths, steps;
  std::vector<double> values;
  Draws(const std::string& name, size_t p, size_t k): paths(p),steps(k),values(p*(k+1)) {
    std::ifstream f(name,std::ios::binary);
    f.read(reinterpret_cast<char*>(values.data()),values.size()*sizeof(double));
    if (!f || f.peek()!=EOF) throw std::runtime_error("Incorrect Gaussian draw file: "+name);
  }
};

std::vector<double> evaluate(const std::vector<double>& eta, double c, int batch, const Draws& d) {
  const size_t n=d.paths, rates=eta.size();
  std::vector<double> w(rates*n),m(rates*n,0),risk(rates);
  for(size_t j=0;j<rates;j++) std::copy_n(d.values.data(),n,w.data()+j*n);
  const double scale=std::sqrt(c/batch);
  for(size_t t=0;t<d.steps;t++) {
    const double* z=d.values.data()+(t+1)*n;
    for(size_t j=0;j<rates;j++) {
      double* wp=w.data()+j*n; double* mp=m.data()+j*n;
      const double step=eta[j];
      for(size_t p=0;p<n;p++) {
        mp[p]=.9*mp[p]+(1-.9)*(wp[p]+scale*z[p]);
        wp[p]-=step*(mp[p]>=0?1.:-1.);
      }
    }
  }
  for(size_t j=0;j<rates;j++) {
    double sum=0;
    for(size_t p=0;p<n;p++)sum+=.5*w[j*n+p]*w[j*n+p];
    risk[j]=sum/n;
  }
  return risk;
}

int main(int argc,char** argv) {
  if(argc!=8) return 2;
  const std::string dir=argv[1]; const int batch=std::stoi(argv[2]);
  const int coarsePaths=std::stoi(argv[3]),selectPaths=std::stoi(argv[4]);
  const int heldoutPaths=std::stoi(argv[5]),reps=std::stoi(argv[6]);
  const size_t steps=4096/batch;
  std::ifstream input(argv[7]);std::vector<double> cnrs;double cnr;
  while(input>>cnr)cnrs.push_back(cnr);
  Draws coarse(dir+"/coarse.bin",coarsePaths,steps),selection(dir+"/selection.bin",selectPaths,steps);
  std::vector<Draws> heldout;
  for(int rep=0;rep<reps;rep++)heldout.emplace_back(dir+"/heldout"+std::to_string(rep)+".bin",heldoutPaths,steps);
  std::vector<double> broad(121);
  for(size_t i=0;i<broad.size();i++)broad[i]=std::exp(std::log(1e-6)+(std::log(2.)-std::log(1e-6))*i/120);
  struct Result {double eta,coarseLoss,selectionLoss,mean,se,nearLo,nearHi;size_t candidates;};
  std::vector<Result> results(cnrs.size()); std::atomic<size_t> next(0);
  auto work=[&]() {
    for(size_t i=next.fetch_add(1);i<cnrs.size();i=next.fetch_add(1)) {
      const double c=1/cnrs[i];auto risks=evaluate(broad,c,batch,coarse);
      std::vector<size_t> order(risks.size());std::iota(order.begin(),order.end(),0);
      std::stable_sort(order.begin(),order.end(),[&](size_t a,size_t b){return risks[a]<risks[b];});
      std::vector<double> centers,grid;
      for(size_t j:order) {
        bool separated=true;
        for(double center:centers)if(std::abs(std::log(broad[j]/center))<=.35)separated=false;
        if(separated)centers.push_back(broad[j]);
        if(centers.size()==3)break;
      }
      for(double center:centers)for(int j=0;j<17;j++)grid.push_back(center*std::exp(std::log(1/1.35)+(2*std::log(1.35))*j/16));
      for(int j=0;j<6;j++)grid.push_back(broad[order[j]]);
      std::sort(grid.begin(),grid.end());grid.erase(std::unique(grid.begin(),grid.end()),grid.end());
      auto selectLoss=evaluate(grid,c,batch,selection);
      const size_t chosen=std::min_element(selectLoss.begin(),selectLoss.end())-selectLoss.begin();
      const double eta=grid[chosen];
      std::vector<double> values;
      for(const Draws& draw:heldout)values.push_back(evaluate({eta},c,batch,draw)[0]);
      const double mean=std::accumulate(values.begin(),values.end(),0.)/reps;
      double variance=0;for(double loss:values)variance+=(loss-mean)*(loss-mean);
      double nearLo=2,nearHi=0;
      for(size_t j=0;j<grid.size();j++)if(selectLoss[j]<=1.05*selectLoss[chosen]){nearLo=std::min(nearLo,grid[j]);nearHi=std::max(nearHi,grid[j]);}
      results[i]={eta,risks[order[0]],selectLoss[chosen],mean,std::sqrt(variance/(reps*(reps-1))),nearLo,nearHi,grid.size()};
    }
  };
  std::vector<std::thread> workers;
  for(size_t i=0;i<std::min<size_t>(12,cnrs.size());i++)workers.emplace_back(work);
  for(auto& worker:workers)worker.join();
  std::cout<<std::setprecision(17);
  for(size_t i=0;i<cnrs.size();i++) {
    const auto& r=results[i];
    std::cout<<cnrs[i]<<','<<batch<<','<<steps<<','<<steps*batch<<','<<r.eta<<','<<r.mean<<','<<r.se<<','<<r.coarseLoss<<','<<r.selectionLoss<<','<<r.nearLo<<','<<r.nearHi<<','<<r.candidates<<'\n';
  }
}
